[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

# Etherscan V2 API key (works across all supported chains)
etherscan_api_key = "${ETHERSCAN_KEY}"

[rpc_endpoints]
anvil = "http://localhost:8545"
optimism-sepolia = "https://rpc.inverter.network/main/evm/11155420"
base-sepolia = "https://rpc.inverter.network/main/evm/84532"
sepolia = "https://rpc.inverter.network/main/evm/11155111"
base-mainnet = "https://rpc.inverter.network/main/evm/8453"
avalanche-fuji = "https://rpc.inverter.network/main/evm/43113"

[etherscan]
optimism-sepolia = { key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/v2/api?chainid=11155420" }
base-sepolia = { key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/v2/api?chainid=84532" }
sepolia = { key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/v2/api?chainid=11155111" }
base-mainnet = { key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/v2/api?chainid=8453" }
avalanche-fuji = { key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/v2/api?chainid=43113" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
